version: 2
models:
  - name: staging_ecommerce_data
    config:
      materialized: table
      schema: staging
      
    
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: session_id
        tests:
          - not_null
        meta:
          original_field: "ActionID"
      - name: customer_id
        tests:
          - not_null
      - name: product_id
      - name: event_timestamp
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null
          - accepted_values:
              values: ['add_to_cart', 'click', 'login', 'logout', 'page_view', 'product_view', 'purchase']